language: go

go:
  - "1.9"
  - "1.10"
  - "master" 

matrix:
  allow_failures:
    - go: master
  fast_finish: true

before_script:
- make init

script:
- make vet
- make dist

deploy:
  provider: releases
  api_key: "$GITHUB_RELEASE_TOKEN"
  skip_cleanup: true
  file_glob: true
  file:
  - dist/*.tar.gz
  - dist/*.zip
  on:
    tags: true

